apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: codec-server-creds
spec:
  secretName: codec-server-creds-tls
  privateKey:
    rotationPolicy: Always
  dnsNames:
  - codec-creds.tmprl-demo.cloud
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
