apiVersion: apps/v1
kind: Deployment
metadata:
  name: codec-server-creds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codec-server-creds
  template:
    metadata:
      labels:
        app: codec-server-creds
    spec:
      containers:
      - image: pvsone/codec-server-creds:1.0.0
        name: codec-server-creds
        imagePullPolicy: Always
        env:
        - name: AUTH0_CLIENT_ID
          value: ${AUTH0_CLIENT_ID}
        - name: AUTH0_DOMAIN
          value: ${AUTH0_DOMAIN}
        - name: AUTH0_CLIENT_SECRET
          value: ${AUTH0_CLIENT_SECRET}
        - name: AUTH0_CALLBACK_URL
          value: https://codec-creds.tmprl-demo.cloud/callback
        - name: TEMPORAL_ORIGIN_URL
          value: https://cloud.temporal.io
        - name: CODEC_BIND_ADDRESS
          value: 0.0.0.0:3000
        - name: CODEC_ENABLE_TLS
          value: "false"
